apiVersion: v1
kind: Pod
metadata:
  name: fc-add-to-alchemist
  namespace: alchemist-processor
  labels:
    app: alchemist-add-processor
  annotations:
    iam.amazonaws.com/role: svc-sandbox-alchemist
spec:
  containers:
  - name:  alchemist-processor-container
    image: opendatacube/datacube-alchemist:latest
    #args: ["/usr/bin/env", "sleep", "600"]
    args: [ "datacube-alchemist", "addtoqueue"]
    resources:
      requests:
        cpu: 1
        memory: 8192Mi
      limits:
        memory: 8192Mi
    tty: true
    stdin: true
    env:
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: svc-sandbox-alchemist
          key: AWS_DEFAULT_REGION
    - name: ALCHEMIST_ADDTOQUEUE_MESSAGE_QUEUE
      value: "alchemist-standard-test"
      #value: "fc-alchemist"
    - name: ALCHEMIST_ADDTOQUEUE_ENVIRONMENT
      value: "datacube"
    - name: ALCHEMIST_ADDTOQUEUE_LIMIT
      value: "11"
    - name: ALCHEMIST_ADDTOQUEUE_CONFIG_FILE
      value: "https://raw.githubusercontent.com/opendatacube/datacube-alchemist/master/examples/fc_config_S2A.yaml"
      #value: "s3://test-results-deafrica-staging-west/test_configs/DEAfrica_ls8_fc_config.yaml"
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: sandbox-datacube
          key: postgres-username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sandbox-datacube
          key: postgres-password
    - name: DATACUBE_CONFIG_PATH
      value: "/opt/custom-config.conf"
    - name: DB_DATABASE
      value: "sandbox"
    - name: DB_HOSTNAME
      value: "database.local"
    - name: DB_PORT
      value: "5432"
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: svc-sandbox-alchemist
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: svc-sandbox-alchemist
          key: AWS_SECRET_ACCESS_KEY
    - name: LOG_LEVEL
      value: "INFO"
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: Never